<div class="cont-pagina"><!-- Cont = Principal -->
   <div class="row">
   	    <div class="col-lg-12 col-md-12 col-sm-12">

		   	   <!-- Titulo -->
	        <div>
	        	   <div class="row">
							   	   <div class="col-lg-12 col-md-12 col-sm-12">
							   	   	    <div>
							   	   	    	    <h4 class="text-center titulo">SERVICIOS</h4>
							   	   	    </div>
							   	   </div>
	        	   </div>
	        </div>

               <div class="cont-formulario"><!-- Cont = Formulario -->
               	   <div class="row">
               	   	   <div class="col-lg-12 col-md-12 col-sm-12">
               	   	   	    <div>

               	   	   	    	   <form class="form-horizontal" role="form" >
											                       <div><!-- Nombre -->
																																				<div class="form-group">
																																				    <label for="nom_servicio" class="col-lg-4 control-label"> <p class="text-label text-left">Nombre :</p> </label>
																																				    <div class="col-lg-8">
																																				       <input type="text" class="form-control " id="nom_servicio">
																																				    </div>
											                         </div>
											                       </div>

											                       <div><!-- Categoria -->
																																				<div class="form-group">
																																				    <label for="categoria_servicio" class="col-lg-4 control-label"> <p class="text-label text-left">Categoria :</p> </label>
																																				    <div class="col-lg-8">
																																				       <input type="text" class="form-control " id="categoria_servicio">
																																				    </div>
											                         </div>
											                       </div>

											                       <div><!-- Subcategoria -->
																																				<div class="form-group">
																																				    <label for="subcategoria_servicio" class="col-lg-4 control-label"> <p class="text-label text-left">Subcategoria :</p> </label>
																																				    <div class="col-lg-8">
																																				       <input type="text" class="form-control " id="subcategoria_servicio">
																																				    </div>
											                         </div>
											                       </div>

											                       <div class="cont-btn"><!-- Btn = grabar , actualizar , emilinar -->
											                           <div class="row">
													                          <div class="col-lg-12 col-md-12 col-sm-12">
													                           	    <div class="text-center"><!-- cont -->
													                           	    	    <button type="button" class="btn btn-success" id="btn_grabar_servicios">Grabar</button>
													                           	    	    <button type="button" class="btn btn-success" id="">Actualizar</button>
													                           	    	    <button type="button" class="btn btn-success" id="">Eliminar</button>
													                           	    </div>
													                           </div>
											                           </div>
											                       </div>
               	   	   	    	   </form>

               	   	   	    </div>
               	   	   </div>
               	   </div>
               </div>

   	    </div>
   </div>
</div>
