<!--
       TIPO         UBICACION         DOCUMNETO
        Css            css        fc_servicios_listado.css
 -->
<div class="cont-pagina"><!-- Conte-Principal  -->
  <div>
 	   <!-- Titulo -->
     <div>
     	   <div class="row">
			   	   <div class="col-lg-12 col-md-12 col-sm-12">
			   	   	    <div>
			   	   	    	    <h4 class="text-center titulo">Modificar / Eliminar</h4>
			   	   	    </div>
			   	   </div>
     	   </div>
     </div>

     <!-- Tabla -->
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
           <div class="cont-table"><!-- Contenedor -->
              <table class="table table-bordered table-hover">
                   <thead><!-- Cabezera tabla -->
                       <tr>
                            <th class="titulo-tabla">Nombre Empresa</th>
                            <th class="titulo-tabla">Telefono</th>
                            <th class="titulo-tabla">Contacto</th>
                            <th class="titulo-tabla">IMG</th>
                            <th class="titulo-tabla">IMG</th>
                       </tr>
                   </thead>

                   <tbody><!-- Cuerpo -->
                       <tr>
                           <td class="cuerpo-tabla">TRON</td>
                           <td class="cuerpo-tabla">441 62 18</td>
                           <td class="cuerpo-tabla"><a href="#">erickdavidmg@gmail.com</a></td>
                           <td class="cuerpo-tabla"><a href="#" title="Modificar"><span class="icon-pencil"></span></a></td>
                           <td class="cuerpo-tabla"><a href="#" title="Eliminar"><span class="icon-cross"></span></a></td>
                       </tr>
                   </tbody>
              </table>
           </div>
        </div>
    </div>

  </div>
</div><!-- Conte-Principal  -->
