<!--
    Estilos Css => Template => balk-footer.css
          ********* Footer *********       -->

<div class="footer_balquimia"><!-- Cont-principal -->
	   <div class="row">
       <div class="col-lg-12 col-md-12 col-sm-12">

       	   <div class="cont-footer"><!-- Contenedor -->
	             <strong>PBX :</strong> ( 2 ) 488 16 16. <br>
	             <strong>Línea gratuita al cliente :</strong> 01 8000 18 TRON ( 8766 ). <br>
	             <strong>Dirección :</strong> Cll 35 N° 4-31 , Cali - Colombia.
           </div><!-- Contenedor -->

       </div>
	   </div>
</div><!-- Cont-principal -->
