<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title> <?= APP_NAME ;?> </title>
      <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS CSS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
      ******************************************************************************************************************-->
      <!-- CSS de Bootstrap -->
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>bootstrap.min.css" media="screen" />

      <!--
      <link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.structure.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.theme.css"  />
      -->


      <?php  if(isset($this->Css) && !empty($this->Css))
      {
       foreach ($this->Css as $Archivo_Css) { ?>
       <link type="text/css"  rel="stylesheet" href="<?= $Archivo_Css ;?>"   />
       <?php }} ?>
      <!-- FIN INLCUSIÓN DE ARCHIVOS CSS
      *******************************************************************************************************************-->

      <!-- librerías opcionales que activan el soporte de HTML5 para IE8 -->
          <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
           <![endif]-->
         </head>
          <body style="width: 80%; margin: 0px auto;">

           <header >

             <div class="contenedor-header"><!-- Cont-Principal -->
                 <div class="row">
                      <div><!-- Cont -->

                           <div class="col-lg-2 col-md-2 col-sm-2"><!-- Logo -->
                              <div>
                                   <img src="<?= BASE_IMG ;?>logo.png" class="logo">
                              </div>
                           </div>

                           <div class="col-lg-10 col-md-10 col-sm-10"><!-- Menu -->

                            <nav class="navbar navbar-default" id="barra_menu">
                              <div class="container-fluid">
                                <div class="navbar-header">
                                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                  </button>
                                  <a class="link_menu navbar-brand" href="#"><span class="inicio"></span></a>
                                </div>

                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                  <ul class="nav navbar-nav">

                                   <!-- Empresas -->
                                   <li class="dropdown">
                                    <a href="#" class="link_menu dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Empresas <span class="caret"></span></a>
                                      <ul class="dropdown-menu" role="menu">
                                        <!-- optiones => Empresas -->
                                        <li><a href="<?= BASE_URL ;?>empresa/administracion_datos" class="link-sub-lista">Administrar datos</a></li>
                                        <li><a href="#" class="link-sub-lista">Listado</a></li>
                                      </ul>
                                    </li>

                                   <!-- Servicios -->
                                   <li class="dropdown">
                                    <a href="#" class="link_menu dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Servicios <span class="caret"></span></a>
                                      <ul class="dropdown-menu" role="menu">
                                        <!-- optiones => Servicios -->
                                        <li><a href="#" class="link-sub-lista">Administrar datos</a></li>
                                        <li><a href="#" class="link-sub-lista">Listado</a></li>
                                      </ul>
                                   </li>
                                  <li><a href="#" class="link_menu">Ingreso al sistema</a></li>

                                  </ul>


                                </div><!-- /.navbar-collapse -->
                              </div><!-- /.container-fluid -->
                            </nav>

                           </div>
                      </div>
                 </div>
             </div><!-- Cont-Principal -->

          </header>

      <!-- Llamado a los Estilos Css = Header , Footer -->
         <link type="text/css" rel="stylesheet" href="<?=BASE_CSS;?>fc_header.css"/> <!-- Header -->
         <link type="text/css" rel="stylesheet" href="<?=BASE_CSS;?>fc_footer.css"/> <!-- Footer -->
         <link type="text/css" rel="stylesheet" href="<?=BASE_CSS;?>font_styles.css"/> <!-- Footer -->
      <!-- Llamado a los Estilos Css = Header , Footer -->

<?= $ContenidoBody;?>
<?php require_once ($RutaFooter);?>

<script src="<?=  BASE_JS ; ?>prefixfree.min.js"                 type="text/javascript">  </script>
<script src ="<?= BASE_JS ; ?>jquery-1.11.1.Oct.10.2014.min.js"  type="text/javascript" ></script>
<script src ="<?= BASE_JQUERY_UI ; ?>jquery-ui.js"               type="text/javascript" ></script>
<script src ="<?= BASE_JS ; ?>bootstrap.js"                      type="text/javascript" ></script>




      <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS JS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
      /////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
      <?php  if(isset($this->Js) && !empty($this->Js))
      {
        foreach ($this->Js as $Archivo_Js){ ?>
        <script   src="<?= $Archivo_Js ;?>" type="text/javascript">  </script>
        <?php }} ?>
    <!-- FIN INLCUSIÓN DE ARCHIVOS JS
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
    </div>
  </body>



  </html>
