<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title> <?= APP_NAME ;?> </title>
      <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS CSS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
      ******************************************************************************************************************-->
      <!-- CSS de Bootstrap -->
      <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>bootstrap.min.css" media="screen" />

      <!--
      <link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.structure.css"  />
      <link type="text/css" rel="stylesheet" href="<?=BASE_JQUERY_UI ;?>jquery-ui.theme.css"  />
      -->


      <?php  if(isset($this->Css) && !empty($this->Css))
      {
       foreach ($this->Css as $Archivo_Css) { ?>
       <link type="text/css"  rel="stylesheet" href="<?= $Archivo_Css ;?>"   />
       <?php }} ?>
      <!-- FIN INLCUSIÓN DE ARCHIVOS CSS
      *******************************************************************************************************************-->

      <!-- librerías opcionales que activan el soporte de HTML5 para IE8 -->
          <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
           <![endif]-->
         </head>
          <body style="width:97.8%; margin: 0px auto;">

           <header>

             <div class="contenedor"><!-- Cont-Principal -->
                  <div class="row" >
                      <!-- Inlucion del partes del header  -->
                          <?php include (APPLICATION_SECTIONS .'header_logo.php');?><!-- Logo = BALQUIMIA -->
                      <!-- Inlucion del partes del header  -->
                  </div>

                  <div class="row">
                          <?php include (APPLICATION_SECTIONS .'header_menu.php');?><!-- Menu -->
                  </div>
             </div><!-- Cont-Principal -->

          </header>

      <!-- Llamado a los Estilos Css = Header , Footer -->

         <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>balk-header_logo.css"  />      <!-- Logo -->
         <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>balk-header_navegador.css"  /> <!-- Barra-Buscar -->
         <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>balk-menu.css"  />             <!-- Menu -->
         <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>font_styles.css"  />           <!-- Font-Style -->
         <link type="text/css" rel="stylesheet" href="<?=BASE_CSS ;?>balk-footer.css"  />           <!-- Footer -->

      <!-- Llamado a los Estilos Css = Header , Footer -->

<?= $ContenidoBody;?>
<?php require_once ($RutaFooter);?>

<script src="<?=  BASE_JS ; ?>prefixfree.min.js"                 type="text/javascript">  </script>
<script src ="<?= BASE_JS ; ?>jquery-1.11.1.Oct.10.2014.min.js"  type="text/javascript" ></script>
<script src ="<?= BASE_JQUERY_UI ; ?>jquery-ui.js"               type="text/javascript" ></script>
<script src ="<?= BASE_JS ; ?>bootstrap.js"                      type="text/javascript" ></script>




      <!-- OCTUBRE 09 DE 2014 -> INCLUSIÓN DE ARCHIVOS JS - REALACIONADOS CON LA VISTA EN PARTUCULAR QUE ESTOY CARGANDO
      /////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
      <?php  if(isset($this->Js) && !empty($this->Js))
      {
        foreach ($this->Js as $Archivo_Js){ ?>
        <script   src="<?= $Archivo_Js ;?>" type="text/javascript">  </script>
        <?php }} ?>
    <!-- FIN INLCUSIÓN DE ARCHIVOS JS
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
    </div>
  </body>



  </html>
