<!--
       TIPO         UBICACION         DOCUMNETO
        Css            css        fc_empresa_registrar.css
        js             js         fc_empresa_registrar.js
 -->
<div class="cont-pagina"><!-- Contenedor Principal -->
	   <div class="row">

	   	   <!-- Titulo -->
        <div>
        	   <div class="row">
						   	   <div class="col-lg-12 col-md-12 col-sm-12">
						   	   	    <div>
						   	   	    	    <h4 class="text-center titulo_registro_modificacion">Registro/ Modificacion Empresas.</h4>
						   	   	    </div>
						   	   </div>
        	   </div>
        </div>

        <!-- Formmulario -->
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="cont-formulario"><!-- Cont = Formulario -->
            	    <form class="form-horizontal" role="form">

                       <div><!-- Nit -->
																									<div class="form-group">
																									    <label for="identificacion" class="col-lg-4 control-label"> <p class="text-label text-left">Nit :</p> </label>
																									    <div class="col-lg-7">
																									       <input type="text" class="form-control input_text" id="identificacion">
																									    </div>
                         </div>
                       </div>

                       <div><!-- Nombre / Reazon Social -->
																									<div class="form-group">
																									    <label for="razon_social" class="col-lg-4 control-label"> <p class="text-label text-left">Nombre/ Razon Social :</p> </label>
																									    <div class="col-lg-7">
																									       <input type="text" class="form-control input_text" id="razon_social">
																									    </div>
                         </div>
                       </div>

                       <div><!-- Direccion -->
																									<div class="form-group">
																									    <label for="direccion" class="col-lg-4 control-label"><p class="text-label text-left">Dirección :</p> </label>
																									    <div class="col-lg-7">
																									       <input type="text" class="form-control input_text" id="direccion">
																									    </div>
                         </div>
                       </div>

                       <div><!-- Telefono -->
																									<div class="form-group">
																									    <label for="nro_telefono" class="col-lg-4 control-label"><p class="text-label text-left">Teléfono :</p> </label>
																									    <div class="col-lg-7">
																									       <input type="text" class="form-control input_text" id="nro_telefono">
																									    </div>
                         </div>
                       </div>

                       <div><!-- Ciudad -->
																									<div class="form-group">
																									    <label for="idmcipio" class="col-lg-4 control-label"><p class="text-label text-left">Ciudad  :</p></label>
																									    <div class="col-lg-7">

																									    <select class="form-control input_text" id="idmcipio">
																																<option value="0">Seleccione un Municipio</option>
																													<?php
																															foreach ($this->Listado_Municipios as $Municpio) {
																																			echo '<option value="'.$Municpio['idmcipio'].'">'.$Municpio['nommcipio'].'</option>';
																																}
																														?>
																										</select>


																									    </div>
                         </div>
                       </div>

                       <div><!-- actividad economica -->
																									<div class="form-group">
																									    <label for="idactividad" class="col-lg-4 control-label"><p class="text-label text-left">Actividad Económica :</p> </label>
																									    <div class="col-lg-7">
																									    <select class="form-control input_text" id="idactividad">
																																<option value="0">Seleccione un Servicio</option>
																													<?php
																															foreach ($this->Servicios as $Servicios) {
																																			echo '<option value="'.$Servicios['idactividad'].'">'.$Servicios['nomactividad'].'</option>';
																																}
																														?>
																										   </select>


																									    </div>
                         </div>
                       </div>

                       <div><!-- Contacto -->
																									<div class="form-group">
																									    <label for="contacto" class="col-lg-4 control-label"><p class="text-label text-left">Contacto :</p> </label>
																									    <div class="col-lg-7">
																									       <input type="text" class="form-control input_text" id="contacto"	>
																									    </div>
                         </div>
                       </div>

                       <div><!-- Email -->
																									<div class="form-group">
																									    <label for="email" class="col-lg-4 control-label"><p class="text-label text-left">Email :</p></label>
																									    <div class="col-lg-7">
																									       <input type="text" class="form-control input_text" id="email">
																									    </div>
                         </div>
                       </div>

                       <div><!-- Password -->
																									<div class="form-group">
																									    <label for="password" class="col-lg-4 control-label"><p class="text-label text-left">Password Empresa :</p></label>
																									    <div class="col-lg-7">
																									       <input type="password" class="form-control input_text" id="password">
																									    </div>
                         </div>
                       </div>

                       <div class="cont-btn"><!-- Btn = grabar , actualizar , emilinar -->
                           <div class="row">
		                          <div class="col-lg-12 col-md-12 col-sm-12">
		                           	    <div class="text-center"><!-- cont -->
		                           	    	    <button type="button" class="btn btn-success" id="btn_grabar">Grabar</button>
		                           	    </div>
		                           </div>
                           </div>
                       </div>

                 </form>
            </div>
        </div>

<div class="modal fade" id="ventana" tabindex="-1"  role="dialog" aria-labelledby="#ventana_error" aria-hidden="true">
	   <div class="modal-dialog ventana-editar-direccion">
	   	   <div class="modal-content "><!-- Contenido de la ventana -->
            <div class="modal-header cabezera-modal-error"><!-- Cabezera-vemtana -->
            	   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            	   <h4 class="text-center">Mensaje del Sistema</h4>
            </div><!-- Cabezera-vemtana -->
            <div class="modal-body" id="texto-mensaje">
                <p id="texto">
                </p>
            	<p>
            </div>
            <br>
            <br>
           <div class="modal-footer">
            	   <button type="button" class="btn btn-default " data-dismiss="modal" aria-hidden="true">Cerrar</button>
            </div>
        </div>
     </div>
</div>



	   </div>
</div>
<br>
<br>
<br>
<br>
