<!--
       TIPO         UBICACION         DOCUMNETO
        Css            css           fc_index.css
        js             js
 -->
<div class="cont-pagina"><!-- contenedor principal -->
	    <div class="row">
	    	   <div><!-- cont -->


           <div  id="cr-slide"><!-- Slider -->
             <div class="col-lg-12  col-md-12  col-sm-12 ">
                <section id="slide"class="carousel slide">
                    <ol class="carousel-indicators">
                      <li data-target="#slide" data-slide-to="0" class="active"></li>
                      <li data-target="#slide" data-slide-to="1"></li>
                      <li data-target="#slide" data-slide-to="2"></li>
                      <li data-target="#slide" data-slide-to="3"></li>
                      <li data-target="#slide" data-slide-to="4"></li>
                    </ol>

                    <div class="carousel-inner">
                       <div class="item active">
                         <a href="#"><img src= "<?= BASE_IMG_SLIDER ; ?>1.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>redtron/comisiones"> <img src="<?= BASE_IMG_SLIDER ; ?>2.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>redtron/red_de_amigos_tron"> <img src="<?= BASE_IMG_SLIDER ; ?>3.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>redtron/planes_de_registro"> <img src="<?= BASE_IMG_SLIDER ; ?>4.jpg" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>redtron/productos_tron"> <img src="<?= BASE_IMG_SLIDER ; ?>5.jpg" class="adaptar"> </a>
                       </div>

                    </div>

                    <a href="#slide" class="left carousel-control" data-slide="prev">
                      <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>

                     <a href="#slide" class="right carousel-control" data-slide="next">
                      <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </section>
              </div>
           </div><!-- Slider -->


	    	   </div>
	    </div>
</div>
