<!--
       TIPO         UBICACION         DOCUMNETO
        Css            css           fc_index.css
        js             js
 -->
<div class="cont-pagina"><!-- contenedor principal -->
	    <div class="row">
	    	   <div><!-- cont -->


           <div  class="cont-slider" id="cr-slide"><!-- Slider -->
             <div class="col-lg-12  col-md-12  col-sm-12 ">
                <section id="slide"class="carousel slide">
                    <ol class="carousel-indicators indicadores-slider">
                      <li data-target="#slide" data-slide-to="0" class="active"></li>
                      <li data-target="#slide" data-slide-to="1"></li>
                      <li data-target="#slide" data-slide-to="2"></li>
                    </ol>

                    <div class="carousel-inner">
                       <div class="item active">
                         <a href="#"><img src= "<?= BASE_IMG ; ?>1.png" class="adaptar"> </a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>"> <img src="<?= BASE_IMG ; ?>2.png" class="adaptar"></a>
                       </div>

                       <div class="item">
                         <a href="<?= BASE_URL ;?>"> <img src="<?= BASE_IMG ; ?>3.png" class="adaptar"></a>
                       </div>
                    </div>

                    <a href="#slide" class="left carousel-control" data-slide="prev">
                      <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>

                     <a href="#slide" class="right carousel-control" data-slide="next">
                      <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </section>
              </div>
           </div><!-- Slider -->


	    	   </div>
	    </div>
</div>
